  #  profiles: 
spring:
  data:
    elasticsearch:
      cluster-name: cluster
      cluster-nodes: 127.0.0.1:9300
  #thymeleaf配置
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: html
    prefix: classpath:/templates/
    suffix: .html
  #database配置
  datasource:
    url: jdbc:mysql://rm-bp102k9m31w3854p4o.mysql.rds.aliyuncs.com:3306/pqdt?rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&serverTimezone=CTT
    driver-class-name: com.mysql.jdbc.Driver
    username: datacenter
    password: mimabutigong
    filters: stat,wall
    maxActive: 100
    initialSize: 10
    minIdle: 1
    maxWait: 60000
    
server: 
  port: 8888
  
logging:
  level:
    com.gk: debug
    org.springframework: off
  
#MyBatis相关配置,无需手动写代码配置mybatis相关设置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gk.elasticsearch.model

#PageHelper相关配置
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql 