package com.gk.elasticsearch.mapper;

import com.gk.elasticsearch.model.Thesis;
import com.gk.elasticsearch.model.ThesisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThesisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    long countByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int deleteByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int insert(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int insertSelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    List<Thesis> selectByExampleWithBLOBs(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    List<Thesis> selectByExample(ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    Thesis selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Thesis record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Thesis record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Thesis record, @Param("example") ThesisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Thesis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_thesis
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Thesis record);
}